openapi: '3.0.3'

info:
  description: Live Loop Backend
  version: 0.1.0
  title: Live Loop Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /location:
    get:
      description: Get coordinate and route of specific shuttle
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BusLocation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    
    BusLocation:
      type: object
      properties:
        bus_id:
          type: integer
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        direction:
          type: string
        active:
          type: boolean
      required:
        - bus_id
        - longitude
        - latitude
        - direction
        - active